default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  port: 5432
  database: jet_log_development
  host: localhost

test:
  <<: *default
  database: jet_log_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: jet_log_production
  username: jet_log
  password: <%= ENV["JET_LOG_DATABASE_PASSWORD"] %>